### ISSUE TITLE
Make spawned features not receive decals

### ISSUE THREAD

**Issue by scaryrabbit** [JayToDaBee/TwelveAngryNodes_4.24#41] opened 2021-02-25 02:16 UTC
Currently, cliffs and features can all receive decals. Should set all those spawned meshes to not receive them.

Something similar to this, but through code :
https://docs.unrealengine.com/en-US/Resources/ContentExamples/Decals/1_5/index.html

**Comment by JayToDaBee** [comment] 2021-02-26 16:56
Duplicate of #37, closing

**Closed by JayToDaBee** 2021-02-26 16:56 UTC
